### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by casper-hansen** [reworkd/perplexity-style-streaming#2]
Hi @asim-shrestha, which license is this repository under? Can it be used commercially?

**Comment by devtanna** [comment]
I would like to know the same :)

**Comment by asim-shrestha** [comment]
Yes it can! A bit lazy to do this but feel free to PR the MIT licence if you'd like

**Comment by devtanna** [comment]
Thank you @asim-shrestha will open a PR with MIT license :)

**Comment by devtanna** [comment]
@asim-shrestha create a PR here > https://github.com/reworkd/perplexity-style-streaming/pull/5
